### ISSUE TITLE
Additional characters in output and garbled server list output 

### ISSUE THREAD

**Issue by purana** [moutten/docker-speedtest-cli#1]
I noticed we get some extra characters parsed in the output... as shown below;

root@noodle:~# docker run --rm moutten/speedtest-cli --server 2629
Retrieving speedtest.net configuration...
Retrieving speedtest.net server list...
Testing from iiNet (203.nn.nn.nn)...
b'Hosted by Telstra (Sydney) [0.54 km]: 9.57 ms'
Testing download speed........................................
Download: 99.20 Mbit/s
Testing upload speed..................................................
Upload: 38.04 Mbit/s

Notice the b character before the Hosted by Telstra line..

In addition when I parse the --list option it ends up rendering incorrectly... and is not readable..

**Comment by moutten** [comment]
I'm not sure why, but this issue was fixed by switching to Python version 2.7.x. I've fixed it on f3f7a6f4c2e691c75be8b11371ce6c26b1e40ba3. If you pull the image again from docker hub, it should be fixed.
